# Generated by Django 3.1.2 on 2020-11-25 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AutocontrolDiabetesOpcional',
            new_name='ACDiabetesOpcional',
        ),
        migrations.CreateModel(
            name='ACDiabetes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucemia_matutina', models.BooleanField(null=True)),
                ('opcional_glucemia_matutina', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('glucemia_post_comida_principal', models.BooleanField(null=True)),
                ('opcional_glucemia_comida_principal', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('fecha_hora_registro', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autocontrol_diabetes', to='api.paciente')),
            ],
        ),
        migrations.AlterField(
            model_name='acdiabetesopcional',
            name='autocontrol_diabetes',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autocontrol_opcional', to='api.acdiabetes'),
        ),
        migrations.AlterField(
            model_name='alertaacdiabetes',
            name='autocontrol_diabetes',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alerta', to='api.acdiabetes'),
        ),
        migrations.DeleteModel(
            name='AutocontrolDiabetes',
        ),
    ]
