# Generated by Django 3.1.4 on 2020-12-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201210_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acdiabetes',
            name='opcional_glucemia_comida_principal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='acdiabetes',
            name='opcional_glucemia_matutina',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
