# Generated by Django 3.1.2 on 2020-10-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201018_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='ecnts',
            field=models.ManyToManyField(blank=True, related_name='paciente_list', to='api.ECNT'),
        ),
        migrations.DeleteModel(
            name='Profesional',
        ),
    ]
