# Generated by Django 3.1.2 on 2020-10-31 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expo_token',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
