# Generated by Django 3.1.2 on 2020-10-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201031_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
    ]
