# Generated by Django 3.1.2 on 2020-10-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201018_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='ultimo_autocontrol',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
