# Generated by Django 3.1 on 2020-10-19 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_paciente_ultimo_autocontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutocontrolDiabetesOpcional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aumento_fatiga', models.BooleanField(blank=True)),
                ('perdida_memoria', models.BooleanField(blank=True)),
                ('cambio_orina', models.BooleanField(blank=True)),
                ('perdida_vision', models.BooleanField(blank=True)),
                ('autocontrol_diabetes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autocontrol_opcional', to='api.autocontroldiabetes')),
            ],
        ),
        migrations.DeleteModel(
            name='AutocontrolDiabetesExtra',
        ),
    ]
