# Generated by Django 3.1.2 on 2020-10-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201031_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], default='F', max_length=9),
        ),
    ]
