# Generated by Django 3.1.2 on 2020-11-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201031_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecnt',
            name='descripcion',
            field=models.CharField(max_length=1024),
        ),
    ]
