# Generated by Django 3.1 on 2020-10-25 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201025_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bod',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
