# Generated by Django 3.1 on 2020-10-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201025_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bod',
            field=models.DateField(),
        ),
    ]
